/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuronaand;

import recursos.PanelTransparente;
import recursos.FondoGrafo;

/**
 *
 * @author dizan
 */
public class ViewNeuronaAND extends javax.swing.JFrame {

    /**
     * Creates new form ViewNeuronaAND
     */
    public ViewNeuronaAND() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelPrincipal = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelEntrenamiento = new javax.swing.JPanel();
        PanelTituloEntrenamiento = new javax.swing.JPanel();
        LabelTituloEntrenamiento = new javax.swing.JLabel();
        PanelEntradas = new javax.swing.JPanel();
        BotonX1Titulo = new javax.swing.JButton();
        BotonX1_1 = new javax.swing.JButton();
        BotonX1_2 = new javax.swing.JButton();
        BotonX1_3 = new javax.swing.JButton();
        BotonX1_4 = new javax.swing.JButton();
        BotonX2Titulo = new javax.swing.JButton();
        BotonX2_1 = new javax.swing.JButton();
        BotonX2_2 = new javax.swing.JButton();
        BotonX2_3 = new javax.swing.JButton();
        BotonX2_4 = new javax.swing.JButton();
        BotonSalidaD = new javax.swing.JButton();
        BotonSalidaD_1 = new javax.swing.JButton();
        BotonSalidaD_2 = new javax.swing.JButton();
        BotonSalidaD_3 = new javax.swing.JButton();
        BotonSalidaD_4 = new javax.swing.JButton();
        BotonEntrenar_1 = new javax.swing.JButton();
        BotonEntrenar_2 = new javax.swing.JButton();
        BotonEntrenar_3 = new javax.swing.JButton();
        BotonEntrenar_4 = new javax.swing.JButton();
        BotonIniciar = new javax.swing.JButton();
        PanelNeurona = new FondoGrafo();
        PanelLinea1 = new PanelTransparente();
        LabelValorX1 = new javax.swing.JLabel();
        TextValorX1 = new javax.swing.JTextField();
        LabelValorW1 = new javax.swing.JLabel();
        TextValorW1 = new javax.swing.JTextField();
        PanelLinea3 = new PanelTransparente();
        TextSumatoria = new javax.swing.JTextField();
        LabelSalidaActivada = new javax.swing.JLabel();
        TextSalidaActivada = new javax.swing.JTextField();
        PanelLinea2 = new PanelTransparente();
        LabelValorX2 = new javax.swing.JLabel();
        TextValorX2 = new javax.swing.JTextField();
        LabelValorW2 = new javax.swing.JLabel();
        TextValorW2 = new javax.swing.JTextField();
        PanelDatos = new javax.swing.JPanel();
        LabelUmbral = new javax.swing.JLabel();
        TextUmbral = new javax.swing.JTextField();
        LabelCoeficienteApr = new javax.swing.JLabel();
        TextCoeficienteApre = new javax.swing.JTextField();
        LabelEstadoFinal = new javax.swing.JLabel();
        PanelPruebas = new javax.swing.JPanel();
        PanelTituloPruebas = new javax.swing.JPanel();
        LabelPruebasTitulo = new javax.swing.JLabel();
        PanelEntradasPruebas = new javax.swing.JPanel();
        BotonX1Titulo1 = new javax.swing.JButton();
        BotonX1_5 = new javax.swing.JButton();
        BotonX1_6 = new javax.swing.JButton();
        BotonX1_7 = new javax.swing.JButton();
        BotonX1_8 = new javax.swing.JButton();
        BotonX2Titulo1 = new javax.swing.JButton();
        BotonX2_5 = new javax.swing.JButton();
        BotonX2_6 = new javax.swing.JButton();
        BotonX2_7 = new javax.swing.JButton();
        BotonX2_8 = new javax.swing.JButton();
        BotonSalidaD1 = new javax.swing.JButton();
        BotonSalidaD_5 = new javax.swing.JButton();
        BotonSalidaD_6 = new javax.swing.JButton();
        BotonSalidaD_7 = new javax.swing.JButton();
        BotonSalidaD_8 = new javax.swing.JButton();
        BotonPrueba1 = new javax.swing.JButton();
        BotonPrueba2 = new javax.swing.JButton();
        BotonPrueba3 = new javax.swing.JButton();
        BotonPrueba4 = new javax.swing.JButton();
        PanelSalida = new javax.swing.JPanel();
        LabelSalida = new javax.swing.JLabel();
        TextSalida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Neurona AND");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PanelPrincipal.setLayout(new java.awt.GridBagLayout());

        PanelTitulo.setLayout(new java.awt.GridBagLayout());

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelTitulo.setText("Neurona AND");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelTitulo.add(LabelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelPrincipal.add(PanelTitulo, gridBagConstraints);

        PanelEntrenamiento.setLayout(new java.awt.GridBagLayout());

        LabelTituloEntrenamiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTituloEntrenamiento.setText("Entrenamiento");

        javax.swing.GroupLayout PanelTituloEntrenamientoLayout = new javax.swing.GroupLayout(PanelTituloEntrenamiento);
        PanelTituloEntrenamiento.setLayout(PanelTituloEntrenamientoLayout);
        PanelTituloEntrenamientoLayout.setHorizontalGroup(
            PanelTituloEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
            .addGroup(PanelTituloEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTituloEntrenamientoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelTituloEntrenamiento)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelTituloEntrenamientoLayout.setVerticalGroup(
            PanelTituloEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelTituloEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTituloEntrenamientoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelTituloEntrenamiento)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        PanelEntrenamiento.add(PanelTituloEntrenamiento, gridBagConstraints);

        PanelEntradas.setLayout(new java.awt.GridBagLayout());

        BotonX1Titulo.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1Titulo.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1Titulo.setText("X1");
        BotonX1Titulo.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX1Titulo, gridBagConstraints);

        BotonX1_1.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_1.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_1.setText("1");
        BotonX1_1.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX1_1, gridBagConstraints);

        BotonX1_2.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_2.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_2.setText("1");
        BotonX1_2.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX1_2, gridBagConstraints);

        BotonX1_3.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_3.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_3.setText("0");
        BotonX1_3.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX1_3, gridBagConstraints);

        BotonX1_4.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_4.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_4.setText("0");
        BotonX1_4.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX1_4, gridBagConstraints);

        BotonX2Titulo.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2Titulo.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2Titulo.setText("X2");
        BotonX2Titulo.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX2Titulo, gridBagConstraints);

        BotonX2_1.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_1.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_1.setText("1");
        BotonX2_1.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX2_1, gridBagConstraints);

        BotonX2_2.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_2.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_2.setText("0");
        BotonX2_2.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX2_2, gridBagConstraints);

        BotonX2_3.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_3.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_3.setText("1");
        BotonX2_3.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX2_3, gridBagConstraints);

        BotonX2_4.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_4.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_4.setText("0");
        BotonX2_4.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonX2_4, gridBagConstraints);

        BotonSalidaD.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD.setText("Salida D");
        BotonSalidaD.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonSalidaD, gridBagConstraints);

        BotonSalidaD_1.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_1.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_1.setText("1");
        BotonSalidaD_1.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonSalidaD_1, gridBagConstraints);

        BotonSalidaD_2.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_2.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_2.setText("0");
        BotonSalidaD_2.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonSalidaD_2, gridBagConstraints);

        BotonSalidaD_3.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_3.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_3.setText("0");
        BotonSalidaD_3.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonSalidaD_3, gridBagConstraints);

        BotonSalidaD_4.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_4.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_4.setText("0");
        BotonSalidaD_4.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        PanelEntradas.add(BotonSalidaD_4, gridBagConstraints);

        BotonEntrenar_1.setBackground(new java.awt.Color(0, 153, 204));
        BotonEntrenar_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEntrenar_1.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrenar_1.setText("Enviar");
        BotonEntrenar_1.setActionCommand("E1");
        BotonEntrenar_1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradas.add(BotonEntrenar_1, gridBagConstraints);

        BotonEntrenar_2.setBackground(new java.awt.Color(0, 153, 204));
        BotonEntrenar_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEntrenar_2.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrenar_2.setText("Enviar");
        BotonEntrenar_2.setActionCommand("E2");
        BotonEntrenar_2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradas.add(BotonEntrenar_2, gridBagConstraints);

        BotonEntrenar_3.setBackground(new java.awt.Color(0, 153, 204));
        BotonEntrenar_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEntrenar_3.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrenar_3.setText("Enviar");
        BotonEntrenar_3.setActionCommand("E3");
        BotonEntrenar_3.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradas.add(BotonEntrenar_3, gridBagConstraints);

        BotonEntrenar_4.setBackground(new java.awt.Color(0, 153, 204));
        BotonEntrenar_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEntrenar_4.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrenar_4.setText("Enviar");
        BotonEntrenar_4.setActionCommand("E4");
        BotonEntrenar_4.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradas.add(BotonEntrenar_4, gridBagConstraints);

        BotonIniciar.setBackground(new java.awt.Color(0, 153, 204));
        BotonIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        BotonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradas.add(BotonIniciar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        PanelEntrenamiento.add(PanelEntradas, gridBagConstraints);

        PanelNeurona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelNeurona.setLayout(new java.awt.GridBagLayout());

        PanelLinea1.setLayout(new java.awt.GridBagLayout());

        LabelValorX1.setText("X1 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        PanelLinea1.add(LabelValorX1, gridBagConstraints);

        TextValorX1.setEditable(false);
        TextValorX1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextValorX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelLinea1.add(TextValorX1, gridBagConstraints);

        LabelValorW1.setText(" W1 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 0);
        PanelLinea1.add(LabelValorW1, gridBagConstraints);

        TextValorW1.setEditable(false);
        TextValorW1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextValorW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        PanelLinea1.add(TextValorW1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        PanelNeurona.add(PanelLinea1, gridBagConstraints);

        PanelLinea3.setLayout(new java.awt.GridBagLayout());

        TextSumatoria.setEditable(false);
        TextSumatoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextSumatoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 0);
        PanelLinea3.add(TextSumatoria, gridBagConstraints);

        LabelSalidaActivada.setText("Y ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 230, 0, 0);
        PanelLinea3.add(LabelSalidaActivada, gridBagConstraints);

        TextSalidaActivada.setEditable(false);
        TextSalidaActivada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextSalidaActivada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        PanelLinea3.add(TextSalidaActivada, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(120, 0, 120, 0);
        PanelNeurona.add(PanelLinea3, gridBagConstraints);

        PanelLinea2.setLayout(new java.awt.GridBagLayout());

        LabelValorX2.setText("X1 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        PanelLinea2.add(LabelValorX2, gridBagConstraints);

        TextValorX2.setEditable(false);
        TextValorX2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextValorX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelLinea2.add(TextValorX2, gridBagConstraints);

        LabelValorW2.setText(" W2 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 70, 0, 0);
        PanelLinea2.add(LabelValorW2, gridBagConstraints);

        TextValorW2.setEditable(false);
        TextValorW2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextValorW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 100);
        PanelLinea2.add(TextValorW2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PanelNeurona.add(PanelLinea2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        PanelEntrenamiento.add(PanelNeurona, gridBagConstraints);

        PanelDatos.setLayout(new java.awt.GridBagLayout());

        LabelUmbral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelUmbral.setText("Umbral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PanelDatos.add(LabelUmbral, gridBagConstraints);

        TextUmbral.setEditable(false);
        TextUmbral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PanelDatos.add(TextUmbral, gridBagConstraints);

        LabelCoeficienteApr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCoeficienteApr.setText("Coeficiente de aprendizaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        PanelDatos.add(LabelCoeficienteApr, gridBagConstraints);

        TextCoeficienteApre.setEditable(false);
        TextCoeficienteApre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PanelDatos.add(TextCoeficienteApre, gridBagConstraints);

        LabelEstadoFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelEstadoFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelEstadoFinal.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        PanelDatos.add(LabelEstadoFinal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        PanelEntrenamiento.add(PanelDatos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        PanelPrincipal.add(PanelEntrenamiento, gridBagConstraints);

        PanelPruebas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPruebas.setLayout(new java.awt.GridBagLayout());

        PanelTituloPruebas.setLayout(new java.awt.GridBagLayout());

        LabelPruebasTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelPruebasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPruebasTitulo.setText("Utilizar neurona entrenada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        PanelTituloPruebas.add(LabelPruebasTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        PanelPruebas.add(PanelTituloPruebas, gridBagConstraints);

        PanelEntradasPruebas.setLayout(new java.awt.GridBagLayout());

        BotonX1Titulo1.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1Titulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1Titulo1.setText("X1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX1Titulo1, gridBagConstraints);

        BotonX1_5.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_5.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_5.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX1_5, gridBagConstraints);

        BotonX1_6.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_6.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_6.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX1_6, gridBagConstraints);

        BotonX1_7.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_7.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_7.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX1_7, gridBagConstraints);

        BotonX1_8.setBackground(new java.awt.Color(0, 185, 176));
        BotonX1_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX1_8.setForeground(new java.awt.Color(255, 255, 255));
        BotonX1_8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX1_8, gridBagConstraints);

        BotonX2Titulo1.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2Titulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2Titulo1.setText("X2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX2Titulo1, gridBagConstraints);

        BotonX2_5.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_5.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_5.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX2_5, gridBagConstraints);

        BotonX2_6.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_6.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX2_6, gridBagConstraints);

        BotonX2_7.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_7.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_7.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX2_7, gridBagConstraints);

        BotonX2_8.setBackground(new java.awt.Color(0, 185, 176));
        BotonX2_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonX2_8.setForeground(new java.awt.Color(255, 255, 255));
        BotonX2_8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonX2_8, gridBagConstraints);

        BotonSalidaD1.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD1.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD1.setText("Salida D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonSalidaD1, gridBagConstraints);

        BotonSalidaD_5.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_5.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_5.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonSalidaD_5, gridBagConstraints);

        BotonSalidaD_6.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_6.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonSalidaD_6, gridBagConstraints);

        BotonSalidaD_7.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_7.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_7.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonSalidaD_7, gridBagConstraints);

        BotonSalidaD_8.setBackground(new java.awt.Color(0, 185, 176));
        BotonSalidaD_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalidaD_8.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalidaD_8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PanelEntradasPruebas.add(BotonSalidaD_8, gridBagConstraints);

        BotonPrueba1.setBackground(new java.awt.Color(0, 153, 204));
        BotonPrueba1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPrueba1.setForeground(new java.awt.Color(255, 255, 255));
        BotonPrueba1.setText("Enviar");
        BotonPrueba1.setActionCommand("P1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradasPruebas.add(BotonPrueba1, gridBagConstraints);

        BotonPrueba2.setBackground(new java.awt.Color(0, 153, 204));
        BotonPrueba2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPrueba2.setForeground(new java.awt.Color(255, 255, 255));
        BotonPrueba2.setText("Enviar");
        BotonPrueba2.setActionCommand("P2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradasPruebas.add(BotonPrueba2, gridBagConstraints);

        BotonPrueba3.setBackground(new java.awt.Color(0, 153, 204));
        BotonPrueba3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPrueba3.setForeground(new java.awt.Color(255, 255, 255));
        BotonPrueba3.setText("Enviar");
        BotonPrueba3.setActionCommand("P3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradasPruebas.add(BotonPrueba3, gridBagConstraints);

        BotonPrueba4.setBackground(new java.awt.Color(0, 153, 204));
        BotonPrueba4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPrueba4.setForeground(new java.awt.Color(255, 255, 255));
        BotonPrueba4.setText("Enviar");
        BotonPrueba4.setActionCommand("P4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        PanelEntradasPruebas.add(BotonPrueba4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelPruebas.add(PanelEntradasPruebas, gridBagConstraints);

        PanelSalida.setLayout(new java.awt.GridBagLayout());

        LabelSalida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelSalida.setText("Salida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        PanelSalida.add(LabelSalida, gridBagConstraints);

        TextSalida.setEditable(false);
        TextSalida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PanelSalida.add(TextSalida, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        PanelPruebas.add(PanelSalida, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        PanelPrincipal.add(PanelPruebas, gridBagConstraints);

        getContentPane().add(PanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNeuronaAND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNeuronaAND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNeuronaAND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNeuronaAND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNeuronaAND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonEntrenar_1;
    public javax.swing.JButton BotonEntrenar_2;
    public javax.swing.JButton BotonEntrenar_3;
    public javax.swing.JButton BotonEntrenar_4;
    public javax.swing.JButton BotonIniciar;
    public javax.swing.JButton BotonPrueba1;
    public javax.swing.JButton BotonPrueba2;
    public javax.swing.JButton BotonPrueba3;
    public javax.swing.JButton BotonPrueba4;
    private javax.swing.JButton BotonSalidaD;
    private javax.swing.JButton BotonSalidaD1;
    private javax.swing.JButton BotonSalidaD_1;
    private javax.swing.JButton BotonSalidaD_2;
    private javax.swing.JButton BotonSalidaD_3;
    private javax.swing.JButton BotonSalidaD_4;
    private javax.swing.JButton BotonSalidaD_5;
    private javax.swing.JButton BotonSalidaD_6;
    private javax.swing.JButton BotonSalidaD_7;
    private javax.swing.JButton BotonSalidaD_8;
    private javax.swing.JButton BotonX1Titulo;
    private javax.swing.JButton BotonX1Titulo1;
    private javax.swing.JButton BotonX1_1;
    private javax.swing.JButton BotonX1_2;
    private javax.swing.JButton BotonX1_3;
    private javax.swing.JButton BotonX1_4;
    private javax.swing.JButton BotonX1_5;
    private javax.swing.JButton BotonX1_6;
    private javax.swing.JButton BotonX1_7;
    private javax.swing.JButton BotonX1_8;
    private javax.swing.JButton BotonX2Titulo;
    private javax.swing.JButton BotonX2Titulo1;
    private javax.swing.JButton BotonX2_1;
    private javax.swing.JButton BotonX2_2;
    private javax.swing.JButton BotonX2_3;
    private javax.swing.JButton BotonX2_4;
    private javax.swing.JButton BotonX2_5;
    private javax.swing.JButton BotonX2_6;
    private javax.swing.JButton BotonX2_7;
    private javax.swing.JButton BotonX2_8;
    private javax.swing.JLabel LabelCoeficienteApr;
    public javax.swing.JLabel LabelEstadoFinal;
    private javax.swing.JLabel LabelPruebasTitulo;
    private javax.swing.JLabel LabelSalida;
    private javax.swing.JLabel LabelSalidaActivada;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTituloEntrenamiento;
    private javax.swing.JLabel LabelUmbral;
    private javax.swing.JLabel LabelValorW1;
    private javax.swing.JLabel LabelValorW2;
    private javax.swing.JLabel LabelValorX1;
    private javax.swing.JLabel LabelValorX2;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelEntradas;
    private javax.swing.JPanel PanelEntradasPruebas;
    private javax.swing.JPanel PanelEntrenamiento;
    private javax.swing.JPanel PanelLinea1;
    private javax.swing.JPanel PanelLinea2;
    private javax.swing.JPanel PanelLinea3;
    private javax.swing.JPanel PanelNeurona;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelPruebas;
    private javax.swing.JPanel PanelSalida;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JPanel PanelTituloEntrenamiento;
    private javax.swing.JPanel PanelTituloPruebas;
    public javax.swing.JTextField TextCoeficienteApre;
    public javax.swing.JTextField TextSalida;
    public javax.swing.JTextField TextSalidaActivada;
    public javax.swing.JTextField TextSumatoria;
    public javax.swing.JTextField TextUmbral;
    public javax.swing.JTextField TextValorW1;
    public javax.swing.JTextField TextValorW2;
    public javax.swing.JTextField TextValorX1;
    public javax.swing.JTextField TextValorX2;
    // End of variables declaration//GEN-END:variables
}
